services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebitDe\ShortcutStatuscodes\:
    resource: '../Classes/*'

  WebitDe\ShortcutStatuscodes\Middleware\ShortcutRedirect:
    arguments:
      $controller: null
